[tool.poetry]
name = "planner"
version = "0.1.0"
description = ""
authors = ["Denis Kuznetsov <kunetsov.den.p@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
llm-sorter = {path = "packages/llm_sorter", develop = true}
pydantic = "^2.8.2"
langserve = "^0.2.2"
sse-starlette = "^2.1.3"
fastapi = {extras = ["standard"], version = "^0.112.0"}
pytest = "^8.3.2"
langchain = "^0.2.13"
services-api = {path = "/common_packages/services_api", develop = true}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
